### PR TITLE
Update test.txt + Re-hashing

### PR DESCRIPTION
**Pull request by BlueStaggo**
The Re-hashing part is for b1.8-preview and b1.8-preview2

### CODE REVIEW

**Comment by nasko222** [comment]
I'll merge all pull requests at once, once they're done. Thanks for doing this. Also one thing, Could you remove any META-INF and "null" files from the jar, thats done to remove any trails of mojang official version signature

**Comment by BlueStaggo** [comment]
Huh, I didn't know that the "null" files were some sort of signature. Also, why can't you put up the preview builds first and then the rest of the devs come all at once later?

**Comment by nasko222** [comment]
Hey uh, why didn't you use b1.8-pre1 base?

**Comment by BlueStaggo** [comment]
Because it's tricky to use it with RetroMCP. I made it as close to pre-1 as possible though.

**Comment by BlueStaggo** [comment]
That would be good. Do you accept the versions with the Beta 1.8 base for now?

**Comment by BlueStaggo** [comment]
Sure, what is the invite?

**Comment by Nicky2024** [comment]
Oh come on nasko I wasn’t talking about TMRP access I just wanted to see what the server looks like now.

**Comment by nasko222** [comment]
The server, as I mentioned, is a private unorganized community full of inside jokes. It's nothing official and the only official relation is that the repo is connected to the server. I can't just add you without the other members approving. RS is selective

**Comment by Nicky2024** [comment]
Alright fine I’ll never get to see what RS looks like now.

**Comment by BlueStaggo** [comment]
@Nicky2024 If you want an early look at Beta 1.8 devs, I've finished the [two](https://github.com/BlueStaggo/the-minecraft-recreation-project/raw/beta/b1.8-preview.jar) [preview](https://github.com/BlueStaggo/the-minecraft-recreation-project/raw/beta/b1.8-preview2.jar) versions.

**Comment by BlueStaggo** [comment]
Not ready yet!!

**Pull request closed without merging**
